### PR TITLE
Integrate improvements to pagerank_updating

### PR DESCRIPTION
**Pull request by ehein6**
This patch integrates the latest changes to the pagerank_updating algorithm from Jason Riedy's stinger fork (http://git.cc.gatech.edu/git/u/eriedy3/stinger.git).

This was done by rebasing selected commits from the sc17 branch onto the dev branch. A new header file was introduced to handle the incompatible changes in how the OMP macro works (`alternative_omp_macros.h`).

---
This change is [Reviewable](https://reviewable.io/reviews/stingergraph/stinger/232)

### CODE REVIEW

**Comment by ehein6** [comment]
Rebased onto https://github.com/stingergraph/stinger/pull/233 to fix the build. After that has been merged, I will rebase onto dev and squash.

**Comment by tgoodyear** [comment]
Is this code still worth merging?

**Comment by tgoodyear** [comment]
Bump. Does this make `pagerank_updating` a suitable replacement for `pagerank` ?

**Comment by ehein6** [comment]
Here are benchmark results for four streaming graphs, batch size of 50K edges. `pagerank_updating` does do better on average.

image

**Comment by davidediger** [comment]
I'd be open to merging if the code was up to date with dev.

**Comment by tgoodyear** [comment]
@ehein6 do you have any explanation for the rmat graph which has iterations taking up to 2 minutes for the first few hundred batches? Also what are the epsilon and max-iteration values for these plots?

**Comment by ehein6** [comment]
image
Here's a comparison using sc16 data, perf looks very good.

**Pull request merged**
