### PR TITLE
Integrated streaming connected components.

### PR DESCRIPTION
**Pull request by ogreen**

### CODE REVIEW

**Comment by ehein6** [comment]
This looks almost ready to merge, one more fix.

The standalone algorithm executables in `src/standalone` have been removed. Please remove `src/standalone/streaming_connected_components_hipc/main.c`

You should instead create a client app that connects to the stinger server, and put the code in `src/clients/algorithms`. Take a look at [betweenness.c](https://github.com/stingergraph/stinger/blob/6feeeaaa8d1c81a50b17a91ed710b77f1e93185f/src/clients/algorithms/betweenness/src/betweenness.c) as an example.

**Comment by ehein6** [comment]
Thanks, that looks good. Please remove commented-out code (keeping a copy for yourself of course) and squash everything into one commit.

**Comment by davidediger** [comment]
@ogreen we're in the process of patching up dev in #181.  When this is merged, all the commits at the beginning of your pull request (that aren't yours) can disappear, but you'll need to rebase against dev and then 'push -f'.  @ehein6 will talk you through it.  Please don't squash yet if you haven't already.  Thanks!

**Comment by ogreen** [comment]
@davidediger , @ehein6 - I had already squashed the commits.
Please keep me posted on what needs to be done.

**Comment by ehein6** [comment]
@ogreen Ok, #181 has been merged. Go ahead and rebase against dev, then push up your commit. That should fix the travis build, and assuming that passes this will be ready to merge.

**Comment by ogreen** [comment]
@ehein6 , can you be a bit more specific on what needs to be done?

**Comment by ehein6** [comment]
@ogreen Squash one more time and we're good to go.

**Comment by ogreen** [comment]
@ehein6 , squashed.
Btw, this is real sqaush: https://www.youtube.com/watch?v=aIZQMQAl44I

**Comment by ehein6** [comment]
@davidediger This is ready to merge.

**Pull request merged**
