### PR TITLE
Update JSON-RPC_API_Doc.md

### PR DESCRIPTION
**Pull request by tgoodyear**
Fix typo `get_data_descriptiona` to `get_data_descriptions`

### CODE REVIEW

**Comment by davidediger** [comment]
@tgoodyear: you want to look over that pull request one more time?

**Comment by tgoodyear** [comment]
Good catch. Fixed

**Comment by davidediger** [comment]
I think it should be "get_data_description", not "get_data_descriptions".  Am I crazy?

**Comment by tgoodyear** [comment]
You're right. Updated.

**Comment by davidediger** [comment]
What a pain for one character, no?  Open source admins...

**Pull request merged**
